"""adding a colom for the finance Page for additional information

Revision ID: 7c09a5f2180b
Revises: 05ca6b2d99b5
Create Date: 2025-10-08 15:47:06.759478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c09a5f2180b'
down_revision = '05ca6b2d99b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_info', sa.String(length=120), nullable=True))

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_info', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('add_info')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('add_info')

    # ### end Alembic commands ###
